version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    image: ignaciodaddario/preentrega-backend
    container_name: preentrega-backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/adopciones
    depends_on:
      - mongo

volumes:
  mongo-data:
